### ISSUE TITLE
Support for per-heading properties

### ISSUE THREAD

**Issue by srid** [fosskers/org-mode#27]
This would be great to have to annotate my diary thoughts with arbitrary metadata, and would be useful in [memoir](https://github.com/srid/memoir).

https://orgmode.org/manual/Property-Syntax.html#Property-Syntax

**Comment by srid** [comment]
By the way, I'd be happy to take a stab at this. I'll open a PR one of these days.

Just learned that org-mode's builtin [time-tracking](https://orgmode.org/manual/Clocking-Work-Time.html) utilizes heading properties. And I'd like to get that visualized in memoir.

**Comment by fosskers** [comment]
I never needed drawers for my initial use of the library, so I didn't implement them. You're the first person to ask for them, so it might be a good opportunity to add them, to make the parser more complete.

**Comment by fosskers** [comment]
I'll be tackling this today.
