### ISSUE TITLE
Blocks under heading triggers parse failure of sub-outline

### ISSUE THREAD

**Issue by srid** [fosskers/org-mode#28]
For the following input,

```org
* Top-level heading
** Second-level heading
This is a paragraph in under this heading. There will be children too (see below)
*** Third-level item
*** Another item
```

... which renders as follows in emacs:

![image](https://user-images.githubusercontent.com/3998/115577101-208d7b00-a292-11eb-9b66-198480a4a16a.png)

... this library parses the structure successfully only up to second-level heading, but it doesn't recognize the structure from third-level, because it consumes them as part of the paragraph block under the second-level heading. Here's the AST it produces:

![image](https://user-images.githubusercontent.com/3998/115577263-43b82a80-a292-11eb-9341-e66aeb9bb65c.png)

**Comment by srid** [comment]
Ah, it works *if* I add a newline after the block paragraph. Perhaps this limitation can be documented somewhere (so I'll leave this issue open as reference).

![image](https://user-images.githubusercontent.com/3998/115578277-259efa00-a293-11eb-8f06-e361abd0c9e0.png)

**Comment by fosskers** [comment]
Thanks for the report.

**Comment by srid** [comment]
Thanks for fixing this! This means I don't have to repeatedly insert an extra new line to make the site render properly.

**Comment by srid** [comment]
Ah, spoke too soon - I believe this still exists on master. Using 3f6ff60d9ff0c8bdd569dac76a73200433fe2504

**Comment by fosskers** [comment]
You should still make sure there's a newline after any section *content* before adding the next header.

**Comment by srid** [comment]
Yes, there is always a newline after section heading or heading with content (the next section's heading will start on its own line anyway), as shown in the first screenshot. But the parser will work only if there is an empty line following that newline (as shown in the second screenshot).

Also I think the issue is in the org doc parser, and not section parser. Because this happens even if you have a top-level block that is not followed by an empty line before sections start.
