### ISSUE TITLE
Add a function to extract tags?

### ISSUE THREAD

**Issue by srid** [fosskers/org-mode#29]
I use something like this which is rough but works, but perhaps we can do better using a pandoc-like Walk type.

```haskell
extractTags :: OrgFile -> Set Text
extractTags (Org.OrgFile _meta (Org.OrgDoc blocks sections)) =
  foldMap fromBlocks blocks <> foldMap fromSections sections
  where
    fromSections :: Org.Section -> Set Text
    fromSections (Org.Section heading tags (Org.OrgDoc bs ss)) =
      Set.fromList tags
        <> foldMap fromWords heading
        <> foldMap fromBlocks bs
        <> foldMap fromSections ss

    fromBlocks :: Org.Block -> Set Text
    fromBlocks = \case
      Org.Paragraph ws ->
        foldMap fromWords ws
      _ ->
        mempty

    fromWords :: Org.Words -> Set Text
    fromWords = \case
      Org.Tags ts -> Set.fromList (toList ts)
      _ -> mempty
```

https://github.com/srid/memoir/commit/f75d9d7d621b258b6a03fee0a8f0639d51da1d42#diff-67fe32f714f18086365a4415f3f7b0013f278237ac4c94cb5e7bb8e4d6780d49R119-R141

**Comment by fosskers** [comment]
Sure, we could upstream this easily enough.

**Comment by srid** [comment]
My code assumes that tags can appear anywhere in the heading, but that assumption seems to be wrong as the org manual says that they can appear only at the end:

> Every headline can contain a list of tags; they occur **at the end** of the headline. 

https://orgmode.org/manual/Tags.html

**Comment by srid** [comment]
Which leads to a more general question: should this library adhere strictly to org-mode standards? Or should it allow for some flexibility, noting those differences in README? To me, it does seem like specifying tags in the middle of heading is an useful feature. It is like those hashtags (`#haskell`) we use in Twitter, notebooks, etc.

**Comment by fosskers** [comment]
The policy has been "implement as needed", trending in the direction of standard compliance.
