### ISSUE TITLE
Add todo states to AST

### ISSUE THREAD

**Issue by srid** [fosskers/org-mode#32]
A section node is defined like this currently,

```haskell
data Section = Section
  { sectionHeading :: NonEmpty Words  -- Contains "TODO Hello world"
  , sectionTags    :: [Text]
  , sectionDoc     :: OrgDoc }
```

Note that section text is just a list of `Words`. I'm looking to traverse my org files based on the todo state, and it occurred to me that adding todo state of sections to the `Section` node would make it straight forward to do so.

With this proposed change, the section node would look like:

```haskell
data Section = Section
  { sectionHeading :: NonEmpty Words -- Contains "Hello World"
  , sectionTodoState :: Maybe TodoState  -- Contains Just "TODO"
  , sectionTags    :: [Text] 
  , sectionDoc     :: OrgDoc }

newtype TodoState = TodoState { unTodoState :: Text }
```

For bonus points, we can pass `[Text]` (based on `org-todo-keywords`) to the org-mode parser to override a default list of keywords (TODO, DONE, etc.). Alternatively, we can favour "convention over configuration" and select _any_ capitalized first word in the section heading as todo state.

Ref: https://www.orgmode.org/manual/TODO-Items.html#TODO-Items

**Comment by srid** [comment]
Also I'm curious what you think of using [`Data.Tagged`](https://hackage.haskell.org/package/tagged-0.8.6.1/docs/Data-Tagged.html) in place of newtype. We might as well wrap the Text of tag type.

**Comment by fosskers** [comment]
Thanks for the proposal, I've been thinking about this as well. It shouldn't be too hard to add.

> `Data.Tagged`

I'd rather keep things simple and avoid extra dependencies, especially anything from the kmettoverse.

**Comment by srid** [comment]
Here's a reference implementation: https://github.com/srid/orgself/commit/3d3b482306c6564c984b31b8e9347436875e8966#diff-b4a0d6468b8e404b496d7a9072689a1067a67ff30b2a2dde4a842a9d60f1c90dR6-R37

**Comment by fosskers** [comment]
Also parsing priorities will be easy to do, so I've added that to my TODO list. (Get it? `org-mode` joke :laughing: )
