### ISSUE TITLE
Idea for collaboration

### ISSUE THREAD

**Issue by gitonthescene** [fosskers/org-mode#40]
Hello,  I found your project from the [worg tools list](https://orgmode.org/worg/org-tools/index.html).  First, sorry for the semi-spam nature of this issue.  I had a notion for a project that the org community might find useful and I'm looking for feedback.  Feel free to close this issue if it doesn't sound useful to you.

My idea is to start a [list of org-mode snippets](https://github.com/gitonthescene/org-mode-samples) which can serve as a test bed for people developing tools.  The idea is that having a separate collection of examples makes it easier for others in the community to benefit from the examples developed through communication with users.

Users could use these samples to try to construct minimal examples of issues they're having and/or contribute examples there which others could benefit from.  Exactly how it will take shape is still up in the air.

These samples could also serve as a place to discuss ideas about how to develop the grammar itself.  According to worg, the spec is still in [draft state](https://orgmode.org/worg/dev/org-syntax.html).

There's not much there at the moment.  Mostly because I don't want to commit too early to what seems like it might be useful.  I'll add more examples as I go.

If you like the concept and/or want to contribute and/or just want to offer feedback, I'd very much appreciate it.

Again, sorry for the spam.

**Comment by fosskers** [comment]
Neat, I didn't know it had been added to such a list. And yes, I would be interested in say, basing this library's test suite around your snippets. I think that would be a good way for all the various tooling to agree on what's real.

**Comment by gitonthescene** [comment]
Hi, thanks for replying.  I’ve reached to everyone on that list with a GitHub repository.  The response was unsurprisingly mixed.  The idea was precisely to try to present a neutral ground on which a consensus could be reached.

I don’t doubt that I’ll have to put some more effort into it to draw some participation but I wanted to reach out nonetheless.

Another proposal which I brought up on [org-mode mailing list](https://orgmode.org/list/28097ae6-bd9a-6842-7600-97b220375fbb@yahoo.com/T/#t) was to have an org-mode linter enforce a stricter grammar.  Since it’s a separate process org-mode itself need not be changed at all.  Apps could say they’re only guaranteed to work if the doc lints 100% clean.  This might be another place apps could come together.

I’ve started looking into making an [lsp server](https://microsoft.github.io/language-server-protocol/) based on the [python-language-server](https://github.com/python-lsp/python-lsp-server) and the grammar found [here](https://github.com/tgbugs/laundry/blob/next/laundry/parser.rkt).  I don’t think it should take to long to toss up a prototype.

In any event, thanks again for the interest.  If you feel like contributing please do.  It would be greatly appreciated.  I’ll close this issue for now.

**Comment by fosskers** [comment]
Thanks!
